import { UserStats, Quest, Phantom, EvolutionStage, BazaarItem, JournalEntry } from "./types";

export const INITIAL_USER_STATS: UserStats = {
  level: 12,
  xp: 650,
  xpNeeded: 1000,
  coins: 500,
  legendCoins: 342,
  stamina: 100,
  streak: 8,
  name: "Alaric the Brave",
  title: "Vigilant Wanderer",
  avatarClass: "normal",
};

export const INITIAL_QUESTS: Quest[] = [
  {
    id: "rainbow_plate",
    title: "📸 \"Rainbow Plate\" Nutrition Scan (Vision AI)",
    description: "Submit a meal photo to scan for the 3-Color micronutrient rule.",
    xpReward: 50,
    coinReward: 15,
    completed: false,
    difficulty: "EPIC",
    type: "rainbow_plate",
  },
  {
    id: "brain_dump",
    title: "🎙️ \"Brain Dump Organizer\" (Voice + NLP AI)",
    description: "Record daily voice thoughts to structure action items and stress flags.",
    xpReward: 60,
    coinReward: 20,
    completed: false,
    difficulty: "LEGENDARY",
    type: "brain_dump",
  },
  {
    id: "walk_5_min",
    title: "Walk 5 Minutes",
    description: "Conquer the first mile of the long journey.",
    xpReward: 150,
    coinReward: 25,
    completed: false,
    difficulty: "COMMON",
    type: "walk",
  },
  {
    id: "drink_water",
    title: "Drink Fresh Water",
    description: "Cleanse your spirit with the elixir of life.",
    xpReward: 50,
    coinReward: 10,
    completed: false,
    difficulty: "COMMON",
    type: "water",
  },
  {
    id: "enter_slumber",
    title: "Enter Slumber",
    description: "Recover your vitality for tomorrow's siege.",
    xpReward: 300,
    coinReward: 50,
    completed: false,
    difficulty: "EPIC",
    type: "slumber",
  },
];

export const INITIAL_PHANTOMS: Phantom[] = [
  {
    id: "phantom_1",
    name: "Procrastination Specter",
    level: 1,
    description: "A sluggish phantom of grey dust, swirling dials, and delayed clocks that distracts you from starting your active work.",
    penalties: ["-5 Coins", "Stamina Drain"],
    resolveEfficiency: 65,
    resolved: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDK5xyOxpUHBT6vjL3pq5gERDxZCctfktMywg0qC3p2CyXLdo3QXmKcfOkLZGOfQnoaQkykK5RvTDpRQCJ2hKVSDjlQibrkbVEOe-xtJoyAo-8oRm1c_a7q5hJ3pmPxjIIZ9F51RiEGO9K7ySZyU2N-qp2U1349lbcCnkymSwKCUcsIJrEHaFh26BR5NvoJPslafXkVOfTZ8lONXz6-YDGnu9W1T_6xradcGArHNC-4d-HJOFfyS77aSBVpb44OFx84wO8YOKddZes",
    icon: "skull",
  },
  {
    id: "phantom_2",
    name: "Junk Food Glutton",
    level: 2,
    description: "A shadowy beast made of sugary syrups and greasy snack wrappers, draining your physical energy and mental focus.",
    penalties: ["-10 Coins", "Streak Crash"],
    resolveEfficiency: 32,
    resolved: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAo1qQ1ueayfIq8KLRXPhUGE1MZJbrqpTgaDPuSp3kIZ6HPQ58SDKQxLPq-nsNfowsJbkI7wn-Fuik8sLNgV6U1eWZ6P-Z0Z86_Ctg2vEUw8F-wYmxhYRwCbGS4gu2Lf8yhFiYBX88cOpWMJ8cAZ8s0N0g-YKyLvtfC10Kyg7nTf5xyrfzp1EXKkB6IJG2TBZrW5s8Ngilb6cTXb5C_pBW6QBDvWwTq4uzQrDJcpT5sfGJyWhSHdXh---AsjGp_Xr1PaHI1t_OX5oM",
    icon: "visibility",
  },
  {
    id: "phantom_3",
    name: "Blue Light Fiend",
    level: 3,
    description: "A crouched demon glowing with neon sapphire screen glare, keeping you awake and disrupting your circadian rhythms.",
    penalties: ["-25 Coins", "Mind Fog"],
    resolveEfficiency: 12,
    resolved: false,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCX8erzJe7uVcLchYbxXZKf0ncTOIgA7GeAvwf4tZ2Lr6RKg0miLgJViZXhtD5ppr2mUTxigO_iIAsxrQDz5WUgsWy4zerZPatvOCc8fIOU69rK02rCxNn3VM8yeXsln5zMbIoWl90QLxj5ox-7rZubLiQrLfYDf6xfR4Cb8xE_dmJK8Me8JsgwNSbTQ9_zvsZooBtHe-53gOV4kdQJbLZuVqIlcqK9OEVYdBNdS7QvtKDUy3_HQdVH4UEybM0apctX9ebrbGTpOvg",
    icon: "auto_fix_high",
  },
];

export const INITIAL_STAGES: EvolutionStage[] = [
  {
    id: 1,
    name: "Stage 1: The Forgotten",
    description: "Desolate and aimless, wandering in the mist of lost memory.",
    status: "COMPLETED",
    image: "https://lh3.googleusercontent.com/aida/ADBb0uhD45Ym4bykl-NkShvdrfCM5fgQwQaibcjJdUA7rx0cXfKYaNoZf2ZrTGUNMoebEMV_37EqELmwaEzDQlD1lfmJNITx2E1O-4tDxJD5RBgIZYT4FTLFytk_Vnay8eghRlm77HXXDu0TrzFG83Dc9z9On0tdiZ73vFLYdRr8IW8t2h15Xba_hMRqUSB-89Ck8jtJF9RWYj-7Cf9iNu15py5cgb8BbTkoUUppN5VE4Oz2-f_OJsmpu4w0bbc",
  },
  {
    id: 2,
    name: "Stage 2: The Awakened",
    description: "Experienced traveler with practical gear, hearing the forge's signal.",
    status: "ACTIVE",
    image: "https://lh3.googleusercontent.com/aida/ADBb0ujI7JgGWvOsXRSbnaNOcoSNqJQyt3KFtbGYJ5iebmBFkiSF8I7wqNHErfsKKBPiDJEWkHLxR7xHuvvKnYUGztOXoDbZl5_-GzBcWk7JnY0v2MTQ35UzsA6Rxzx51IsV7B9SU2sGA4jBU7HXbDrG4Qqqk_yWRJTn0A9KTszXqgxfOsd-fBPgVIGcmBedCYchx6pW4PezA41cLkot05AN0MyYQudw1uIQlIToPI8o5P98_pfVhCZbzKsEu8Q",
    bonus: {
      title: "Defensive Bonus",
      description: "Increases block chance by 15% during focus hours.",
      icon: "shield",
    },
  },
  {
    id: 3,
    name: "Stage 3: The Scholar",
    description: "Unraveling runic paths and rewriting the soul's heavy ledger.",
    status: "LOCKED",
    xpToUnlock: 350,
    image: "https://lh3.googleusercontent.com/aida/ADBb0uj_eODXm8Tvnvn6z1cfqce0pTp3BBK_R6W2m5TF_kY6iTOhMGGI0dtzSLqhK2XpTwBLp68VQbrNEfsRQjfm3aYZXIRU3TvbbQFKPGu5iiFkhALw-d4MYNI2tc-IFD-9443dTtIY94JQMvcG3H84CPIRiF-MTFXeMIqwz1wKxQ5Tk3f3DtmvLfVTSOS_JlalSKVGIrUz1o2jZNWHW66nTg9-n-t0I8S9-mqvCtiLkKW80tK7myalLj0NCJg",
    bonus: {
      title: "Deep Focus Mastery",
      description: "Unlocks historical search expansions in the margins.",
      icon: "menu_book",
    },
  },
  {
    id: 4,
    name: "Stage 4: The Ascendant",
    description: "Manifesting the bright mystic fire with unbreakable willpower.",
    status: "LOCKED",
    image: "https://lh3.googleusercontent.com/aida/ADBb0uhDipF2zXsTppoRraF1RvtOYjkTQwPCjERHPnamUlUr8RZM_6haCMZs7jVTQR9KFujbR4p7EOpc9r266prTqMtqu4vI5HcQ1IfyticHA7ufyoY4uy10XNZemyA4LG6hjtFwcCkdpwAuyf4Kh0sS4jJta-S_2zisJ4LKD7TfCcMUyUmivN9q1-mcz84qhTIA2hOgAMdr7AXInHmHazSriQgh8C2A4UtLIiy2y9zZPs4g7uiGTc6ebUkAIwY",
    bonus: {
      title: "Divine Aura",
      description: "Grants 20% cheaper artifacts in the Gilded Bazaar.",
      icon: "stars",
    },
  },
  {
    id: 5,
    name: "Stage 5: The Eternal",
    description: "The ultimate transcended form, an master of continuous discipline.",
    status: "LOCKED",
    image: "https://lh3.googleusercontent.com/aida/ADBb0uh41BioBVyGQhJlsmik1xhfJBfXGwwDn_XB-8z9wHB5zD0j2U6hpM76HYcpns36L6r5qCvfBUPKNZQAkhsLUrQgTFhnvmy8NHgQK7RoWNU0dRA_ZvuyGQ1xI3rLbG2kOSmjUjOmZ2BdiC_gz1ixBVfCa_k9HYfzteLzfnKqz1xDdjsMTg4bXnLXMPz-4wXHmfyi24AY2qJ1Pl-iHsVhi6OlTXT2yh2LztGdDZBJS0wNhLynpEI_xccMYg",
    bonus: {
      title: "Timeless Aegis",
      description: "Immunity to streak decay from all external distractions.",
      icon: "verified",
    },
  },
];

export const INITIAL_BAZAAR_ITEMS: BazaarItem[] = [
  {
    id: "crystal_boost",
    name: "Concentrated Focus Elixir",
    description: "Focus Elixir: Double XP",
    cost: 75,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuB0oTSMsvD7NI-zdyE9CPPcSR1eOhO5wqa5wASEojwhOk8Oug2fc6vJCGrDSXQvV-xRWokYw9aJBX6VFgHski5Yv3WpNWryNSWs68zmzPQI7vOVKAXIno4cg0YwKFQrJ4HP7C3xPs033u75zyo0p_KFgroMkuUc57ZQru1_T1Dst4T0qsB4AhiKrgWWfHASQxbJN9fvepAFAU3ds2zvOXT4muL3k1F8SW36zWmdh9QnAR8sptAItQWOpNXmrxVL7KdefS-4GonI3SQ",
    purchased: false,
    active: false,
    effect: "Double XP active!",
  },
  {
    id: "streak_shield",
    name: "Aegis Shield of Focus",
    description: "Custom Shield: Protect streak",
    cost: 120,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDg6gGPniFnz3gLsuNvR5StIOvgso1iX3sn445JwTX_EDN_ySa-tJbBHNUuFdWCM4geomAawMeRZrVlZUpvGFi3_xFbyZPO-z2C_3HF2DmyG_Jg23zJxoNnA5tlwsZI-7fPoB7c6hE9XH6ZuwnWUjN1IZB2cN3yKWaJe61KitXdhIQljaG8pQA4-6wMefSiYIBbW29Pv0xWZQdK1xQslmWsIeuAdCdG3G42YtQcwgW1o5-5IlkfPcQC7-ZLqOyQhHWAld3JEQAx2Rc",
    purchased: false,
    active: false,
    effect: "Streak protection armed.",
  },
  {
    id: "curse_breaker",
    name: "Sovereign Homework Scroll",
    description: "Homework Scroll: Clear mind blocks",
    cost: 200,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuALbXXfLDemnSFCoKZq-gdnqpa4kU1yCtu26TT29LaTPZJr9o0vz-NoIYtKacbe4Eaz3HcGtHg5N-UlCQeXPSBGEmakmyQCA-xwCdOl_kDOeUbJvL3WqJHGl6F8PLZFNC3LScYUWYNfCp0H1ttL4ilefmDcCJTH5rZNo78tsrtTA61Dqp6ar1EPmS-6D41IfEp0o83KKnsFsoL5EBt6_pAlV1gmkP7WZ_jZZFMGl3CPb2P1VjDYzjrpfcbWF2QeMlynlcxkNVzOZBU",
    purchased: false,
    active: false,
    effect: "All negative curses purged.",
  },
  {
    id: "ancient_cape",
    name: "Ancient Gilded Cape",
    description: "Outfit: Character appearance modifications",
    cost: 450,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDOYBpK8Zk4i7tbm2EypzY7xyG4ewc1hfg4-r0y9YU7gf0Svn3PflO7ONn_51zsDrn2eO8j9R0X_aPOaFNODltXEwoHKqxSnZ0aFJvlVqtSmpeEB2QTzWVAKE67QS3uJddLou2E9U6BE5V_bXTnwIja06MXVufLuepC-i4ZhK5ZKdEj6HJ52Wd_cKTRZGmY7LvFo7g7VK_03YuC1_cvvzucZDFae7QYBXJOEYYleWOTfaaZmwlF9YA6VxVsXXLv61SIxvG6E2RsVYA",
    purchased: false,
    active: false,
    effect: "Aesthetic master level cape equipped.",
  },
  {
    id: "scholar_soundtrack",
    name: "Real-Life Sanctuary Break",
    description: "Breaks: Claim a 15-min guild break",
    cost: 90,
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIS8ffzsE-Kkj9b86YDozZYr2rytttVhPwZR49MX-BnTitPpVIdKdr1pNQ5QckpPQL8jr9tb5B0U1_WUeNgurFHQlQNXp8D6CPd0OgyuobW8UOA62SkueE3vUSwdQthvlUc2K82RtwdLz1SkBkF2lnHqN_vwalgT6u50fCtI31YFP1UUpqi4RfcgWugnk6SaQ6HDKvuMx2LqdcchyDb91ooDJo58O69MVpPIoZbizyNC5m-DXk_B7Xzn3ArKxa7ps_YoKlKdm7TQU",
    purchased: false,
    active: false,
    effect: "Enables binaural focus tones.",
  },
];

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: "entry_1",
    timestamp: "May 25, 2026",
    text: "Decided to start the journey. The iron road was cold, but today I drank water and finished my morning meditation walk. Feeling a subtle spark.",
    mood: "Reflective",
  },
  {
    id: "entry_2",
    timestamp: "May 26, 2026",
    text: "Stood face to face with the Sloth Behemoth. Handled my day's chores with focus. Purged a bit of dust. Tomorrow we continue climbing.",
    mood: "Determined",
  },
];
